server:
  port: 11096

spring:
  application:
    name: hydro-meteo-mock

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.hydrometeomock.controller 